//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurTable
    {
        public long PropId { get; set; }
        public int nCanonId { get; set; }
        public System.DateTime dtReportDate { get; set; }
        public int nTerOtdelenie { get; set; }
        public int nTerPodrazdel { get; set; }
        public decimal vProcent { get; set; }
    }
}
