//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableSource
    {
        public long LineId { get; set; }
        public long nPokazatelId { get; set; }
        public string vPeriodType { get; set; }
        public System.DateTime dtStartDate { get; set; }
        public System.DateTime dtEndDate { get; set; }
        public string vTerritoryId { get; set; }
        public decimal nValue { get; set; }
    }
}
